default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5

development:
  <<: *default
  database: bws_mobile_production
  username: deployer
  password: 1q3e!Q#E
  schema: bws_mobile
  host: 107.170.29.107

test:
  <<: *default
  database: bws_mobile_test
  username: deployer
  password: 1q3e!Q#E
  schema: bws_mobile
  host: 127.0.0.1

production:
  <<: *default
  database: bws_mobile_production
  username: deployer
  password: 1q3e!Q#E
  schema: bws_mobile
  host: 107.170.29.107
